qr_server/qr_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
]

qr_server/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.views.generic import TemplateView

from . import views

app_name = "users"

urlpatterns = [
    path("", views.UsersHome.as_view(), name="home"),
    path("login/", views.LoginUser.as_view(), name="login"),  # "users:login"
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.UserPasswordChange.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "register/done/",
        TemplateView.as_view(template_name="users/register_done.html"),
        name="register_done",
    ),
    path(
        "password-reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("register/", views.RegisterUser.as_view(), name="register"),
]

qr_server/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    qr_code = models.ImageField(upload_to='qr_codes/%Y/%m/%d/', blank=True, null=True)
    patronymic = models.CharField(max_length=150, blank=True, null=True)
    is_scanned = models.BooleanField(default=False)

qr_server/users/forms.py
import datetime
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    PasswordChangeForm,
)


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(attrs={"class": "form-input"}),
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

    class Meta:
        model = get_user_model()
        fields = ["username", "password"]


class RegisterUserForm(UserCreationForm):  # (forms.ModelForm)
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(attrs={"class": "form-input"}),
    )
    # password = ..
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )
    password2 = forms.CharField(
        label="Повтор пароля",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]
        labels = {
            "email": "Email",
            "first_name": "Имя",
            "last_name": "Фамилия",
        }
        widgets = {
            "email": forms.TextInput(attrs={"class": "form-input"}),
            "first_name": forms.TextInput(attrs={"class": "form-input"}),
            "last_name": forms.TextInput(attrs={"class": "form-input"}),
        }

        # def clean_password2(self):
        #     cd = self.cleaned_data
        #     if cd["password"] != cd["password2"]:
        #         raise forms.ValidationError("Пароли не совпадают!")
        #     return cd["password"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует.")
        return email


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"class": "form-input"}),
    )

qr_server/users/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, ListView

from .forms import (
    LoginUserForm,
    RegisterUserForm,
    UserPasswordChangeForm,
)
from .models import User
from .utils import DataMixin


class UsersHome(DataMixin, ListView):
    model = get_user_model()
    template_name = "users/index.html"
    context_object_name = "users"
    title_page = "Главная страница"
    paginate_by = 15

    def get_queryset(self):
        return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mixin_context = self.get_mixin_context(context)
        return mixin_context
    


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {"title": "Авторизация"}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = "users/register.html"
    extra_context = {"title": "Регистрация"}
    success_url = reverse_lazy("users:register_done")


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"


class CustomPasswordResetView(PasswordResetView):
    template_name = "users/password_reset_form.html"
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        if not User.objects.filter(email=email).exists():
            messages.error(self.request, "Пользователь с таким email не найден.")
            return self.form_invalid(form)
        return super().form_valid(form)

qr_server/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <table class="table-page" border=0 cellpadding="0" cellspacing="0">
        <tr><td valign=top>
            {% block mainmenu %}
            <div class="header">
                <ul id="mainmenu" class="mainmenu">
                    <li class="logo">
                        <a href="{% url 'users:home' %}">Главная страница</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="last"><span>{{ user.username }}</span> |
                        <form style="display:inline-block" method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button class="logout-btn">Выйти</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="last">
                        <a href="{% url "users:login" %}">Войти</a> | <a href="{% url "users:register" %}"> Регистрация</a>
                    </li>
                    {% endif %}
                </ul>
                <div class="clear"></div>
            </div>
            {% endblock mainmenu %}

<!-- Блок контента -->
	<div class="content-text">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Конец блока контента -->
{% block navigation %}
{% endblock navigation %}
</td></tr>

<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2024 made by madvln</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

qr_server/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Список пользователей</h1>
    <table>
        <thead>
            <tr>
                <th>Фамилия</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>QR Код</th>
                <th>Сканирован</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.patronymic }}</td>  <!-- Замените на нужное поле для отчества -->
                    <td>
                        {% if user.qr_code %}
                            <img src="{{ user.qr_code.url }}" alt="QR Код" style="width: 50px; height: 50px;">
                        {% else %}
                            Нет QR кода
                        {% endif %}
                    </td>
                    <td>
                        <input type="checkbox" disabled {% if user.is_scanned %}checked{% endif %}>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block navigation %}
<p>Navigation</p>
{% endblock navigation %}

qr_server/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p>
      <label class="form-label" for="{{ f.id_for_label }}">
        {{ f.label }}
      </label>
      {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit"a>Войти</button></p>
    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
</form>
{% endblock content %}

qr_server/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. 
    <a href="{% url 'users:profile' %}">Вернуться в профиль</a>.
</p>

{% endblock content %}

qr_server/users/templates/users/password_change_form.html
{% extends 'base.html' %} {% block content %}
<h1>Изменение пароля</h1>

<form method="post">
  {% csrf_token %}
  <div class="form-error">{{ form.non_fields_errors }}</div>
  {% for f in form %}
  <p>
    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>
    {{ f }}
  </p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}

  <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock content %}

qr_server/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. Используйте его для
    <a href="{% url 'users:login' %}">входа в ситсему</a>.
</p>

{% endblock content %}

qr_server/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %} {% block content %}
<h1>Новый пароль</h1>

<form method="POST">
  {% csrf_token %}
  <div class="form-error">{{ form.non_field_errors }}</div>
  {% for f in form %}
  <p>
    <label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }} </label>
    {{ f }}
  </p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}

  <p><button type="submit" a>Сохранить</button></p>
</form>
{% endblock content %}

qr_server/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock content %}

qr_server/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

qr_server/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>
<!-- Секция для сообщений -->
{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
			{{ message }}
		</li>
		{% endfor %}
	</ul>
{% endif %}

{% endblock content %}

qr_server/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for f in form %}
    <p>
      <label class="form-label" for="{{ f.id_for_label }}">
        {{ f.label }}
      </label>
      {{ f }}
    </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit"a>Регистрация</button></p>
</form>
{% endblock content %}

qr_server/users/templates/users/register_done.html
{% extends 'base.html' %} {% block content %}
<h1>Добро пожаловать!</h1>

<p>
  Вы успешно зарегистрировались на сайте! Для входа в систему необходимо
  авторизоваться по
  <a href="{% url 'users:login' %}">ссылке</a>.
</p>

{% endblock content %}